kind: pipeline
type: docker
name: alpine-amd64-image

# Trigger conditions
trigger:
  branch:
    - '3.20'
    - 'main'
  event:
    - custom
    - push
    - pull_request

# Pipeline steps
steps:

  # Build image
  - name: image-build
    image: plugins/docker
    when:
      branch:
        - '3.20'
      event:
        - push
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/alpine
      tags:
        - latest
        - '3.20'
        - '3.20.3'

  # Test built image
  - name: docker-test
    image: kernel528/alpine:latest
    when:
      branch:
        - 'main'
      event:
        - push
    commands:
      - cat /etc/alpine-release
      - uname -a

  # Post slack notification
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
    when:
      status:
        - failure
        - success
