kind: pipeline
type: docker
name: 3.21-alpine-amd64

trigger:
  branch:
    - '3.21'
  event:
    - pull_request

# Build the docker image for amd64 architecture
steps:
  - name: amd64-image-build
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_REPO:
        from_secret: docker_repo
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_repo_alpine
      tags:
        - latest
        - '3.21'
        - '3.21-drone-build-${DRONE_BUILD_NUMBER}-amd64'
        - '3.21.2'
        - '3.21.2-drone-build-${DRONE_BUILD_NUMBER}-amd64'

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
---

kind: pipeline
type: docker
name: main-alpine-amd64

trigger:
  event:
    - push
    - tag
  branch:
    - main

# Build the docker image for the main branch & tagged release
steps:
  - name: main-docker-image-build
    image: plugins/docker
    environment:
      DOCKER_REPO:
        from_secret: docker_repo
    when:
      event:
        - tag
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo:
        from_secret: docker_repo_alpine
      tags:
        - ${DRONE_TAG}

  # Test docker image
  - name: latest-alpine-amd64-test
    image: ${DOCKER_REPO}/:latest
    environment:
      DOCKER_REPO:
        from_secret: docker_repo_alpine
    when:
      branch:
        - main
      event:
        - push
    commands:
      - cat /etc/alpine-release
      - uname -a

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts