pipeline:
  #docker-alpine:
    #when:
      #branch: "3.18"
  alpine3:
    when:
      branch: main
      event: push
    image: kernel528/alpine:latest
    secrets: [ docker_username, docker_password ]
    dockerfile: Dockerfile
    tag:
      - latest
      - 3.18
      - 3.18.4
      - 3.18.4-${DRONE_COMMIT:0:8}-drone-build-${DRONE_BUILD_NUMBER}

  # Post notification to slack channel
    commands:
      - "uname -a"
      - "cat /etc/alpine-release"

  # Post notification to orpheus-alerts slack channel
  slack:
    when:
      status:
        - success
        - failure
      event:
        - push
        - tag
    image: plugins/slack
    channel: orpheus-alerts
    webhook: https://hooks.slack.com/services/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
    template: >
      Drone build {{uppercase build.status}} for {{ build.link }} with git commit {{ truncate build.commit 8 }} to git branch ({{ build.branch }}) by {{ build.author }}.
