kind: pipeline
type: docker
name: docker

trigger:
  branch:
    include:
      - main
      - 3.18
  event:
    include:
      - push

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/alpine
      tags:
        - latest
        - 3.18
        - 3.18.4

  - name: notify
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
    when:
      status:
        - failure
        - success